services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: flights-image:latest

    ports:
      - "5005:80"

    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

